In [1]:
import torch

In [2]:
class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Sequential(
            torch.nn.Linear(3,10),
            torch.nn.LeakyReLU(),
            torch.nn.Linear(10,50),
            torch.nn.Sigmoid(),
            torch.nn.Linear(50,5)
        )

    def forward(self, x):
        out = self.layer(x)
        return out

m = Model()

In [4]:
for c in m.children():
    print(c)

Sequential(
  (0): Linear(in_features=3, out_features=10, bias=True)
  (1): LeakyReLU(negative_slope=0.01)
  (2): Linear(in_features=10, out_features=50, bias=True)
  (3): Sigmoid()
  (4): Linear(in_features=50, out_features=5, bias=True)
)


In [415]:
input = x[0]

print(m.layer[0](input))
print(m.layer[1](input))
print(m.layer[2](input))

tensor([-0.1767,  1.0061,  0.8574, -0.8538,  2.0338, -0.4518, -1.9040, -0.0412,
        -1.9899, -0.4397], grad_fn=<AddBackward0>)
tensor([-0.0279, -0.0179, -0.0079])


RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x3 and 10x50)

In [390]:
m = Model()

In [396]:
batch_size = 10000
n_dim = 1 

first_col = torch.randn(batch_size, 1)
x = torch.concat((first_col - 1, first_col, first_col + 1),1)
y = torch.concat((first_col -2, first_col - 1, first_col, first_col + 1, first_col + 2),1)

In [397]:
optimizer = torch.optim.Adam(m.parameters(), lr=0.1)
loss_fn = torch.nn.MSELoss()

for i in range(10000):
    y_hat = m(x)
    loss = loss_fn(y_hat, y)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if i%1000 == 0:
        print(loss.item())

    

    

0.000515805440954864
1.0301686415914446e-05
8.405470907746349e-06
8.201057426049374e-06
1.1025080311810598e-05
1.281882305192994e-05
0.00046405510511249304
0.00018091585661750287
1.5329980669775978e-05
6.153989943413762e-06


In [401]:
input = torch.tensor([-13, -12, -11]).float()

print(input)
m(input)

tensor([-13., -12., -11.])


tensor([-5.8605, -4.8607, -3.8606, -2.8604, -1.8606], grad_fn=<AddBackward0>)

In [331]:
x[0].type

<function Tensor.type>

In [330]:
input.type

<function Tensor.type>

In [60]:
m.requires_grad_

<bound method Module.requires_grad_ of Model(
  (layer): Sequential(
    (0): Linear(in_features=3, out_features=5, bias=True)
    (1): ReLU()
    (2): Linear(in_features=5, out_features=1, bias=True)
    (3): Sigmoid()
  )
)>

In [165]:
import torch.nn as nn 

# Example of target with class indices
loss = nn.CrossEntropyLoss()
input = torch.randn(3, 5, requires_grad=True)
target = torch.empty(3, dtype=torch.long).random_(5)
output = loss(input, target)

In [176]:
y_hat.shape

torch.Size([50, 2])

In [177]:
input.shape

torch.Size([3, 5])

In [178]:
target.shape

torch.Size([3])

In [179]:
y.shape

torch.Size([50])

In [126]:
loss_fn(y.view(1,-1), y_hat.view(1,-1))

tensor(201.3054, grad_fn=<DivBackward1>)