# [Tensors Basics](https://pytorch.org/tutorials/beginner/basics/tensor_tutorial.html)

Tensors are multidimensional arrays and are the basis for Deep Learning frameworks. They are analogous to numpy.ndarrays, but are more convenient because:
- they can be processed in GPUs
- they are optimized to calculate gradients automatically

In [5]:
import torch
import numpy as np

## Initializing Tensors

Tensors can be initialized in many ways:

1. Directly from lists

In [8]:
tensor_from_data = torch.tensor([[2,3], [4,5]])
tensor_from_data

tensor([[2, 3],
        [4, 5]])

2. From a numpy array

In [9]:
array = np.array([1,2,3,4])

tensor_from_numpy = torch.from_numpy(array)
tensor_from_numpy

tensor([1, 2, 3, 4])

3. from another tensor: by copying the dtype and shape of the original tensor

In [12]:
tensor_from_tensor = torch.ones_like(tensor_from_numpy)
tensor_from_tensor

tensor([1, 1, 1, 1])

4. with random or constant values

In [15]:
shape = (4,4)

tensor_ones = torch.ones(shape)
print(tensor_ones)

tensor_zeros = torch.zeros(shape)
print(tensor_zeros)

tensor_rand = torch.rand(shape)
print(tensor_rand)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0.9027, 0.6215, 0.7238, 0.2466],
        [0.4262, 0.0372, 0.1556, 0.4464],
        [0.3473, 0.6230, 0.8679, 0.8904],
        [0.9050, 0.3615, 0.4410, 0.2664]])


## Properties of Tensors

The most common attributes of tensors are:
- shape = # rows, # columns
- type = type of the entries (all of them have to be of the same type)
- device = device the tensor is stored on

In [17]:
tensor_rand = torch.rand((5,3))

print(f'Shape of tensor: {tensor_rand.shape}')
print(f'Type of tensor: {tensor_rand.dtype}')
print(f'Device the tensor is stored on: {tensor_rand.device}')

Shape of tensor: torch.Size([5, 3])
Type of tensor: torch.float32
Device the tensor is stored on: cpu


Tensors are, by default, created on CPU. If we want to use them on GPU, we need to explicitely send them there.

In [19]:
if torch.cuda.is_available():
    tensor = tensor_rand.to('cuda')
else:
    print('GPU not available.')


GPU not available.


## Tensor operations

Tensor operations are very similar to what you can do on numpy for np.arrays.

In [27]:
tensor = torch.tensor([[1,2], [3,4], [5,6]])
tensor

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [24]:
# Select the second row
tensor[1, :]

tensor([3, 4])

In [26]:
# Select the first column
tensor[:, 0]

tensor([1, 3, 5])

In [28]:
# Select the last column
tensor[:, -1]

tensor([2, 4, 6])

In [30]:
# Concatenate tensors with compatible shapes
tensor_2 = torch.ones(3,2)

torch.cat([tensor, tensor_2], dim=1)

tensor([[1., 2., 1., 1.],
        [3., 4., 1., 1.],
        [5., 6., 1., 1.]])

In [33]:
# multiply two matrices 

m1 = torch.tensor([ [2,0], 
                    [0,2]])
                    
m2 = torch.tensor([ [1,2],
                    [7,4]])

m3 = m1 @ m2
m3

tensor([[ 2,  4],
        [14,  8]])

In [34]:
# multiply two matrices element-wise

m1 = torch.tensor([ [2,0], 
                    [0,2]])
                    
m2 = torch.tensor([ [1,2], 
                    [7,4]])

m3 = m1 * m2
m3

tensor([[2, 0],
        [0, 8]])

**Bridge with NumPy**

numpy.arrays and torch.tensors can share the same CPU storage (address) by using the numpy() function. Changing one will change the other as well.

In [35]:
tensor = torch.tensor([2])
array = tensor.numpy()

print(f'tensor: {tensor}, array: {array}')

array += 1

print(f'tensor: {tensor}, array: {array}')


tensor: tensor([2]), array: [2]
tensor: tensor([3]), array: [3]


In [37]:
array = np.array([1,2])
tensor = torch.from_numpy(array)

print(f'tensor: {tensor}, array: {array}')

tensor += 1

print(f'tensor: {tensor}, array: {array}')

tensor: tensor([1, 2]), array: [1 2]
tensor: tensor([2, 3]), array: [2 3]
